const ActionTypes = {
   PRODUCTS_LOADING: "PRODUCTS_LOADING",
   PRODUCTS_ERROR: "PRODUCTS_ERROR",
   PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
   PRODUCTS_SORTING: "PRODUCTS_SORTING",
}
export default ActionTypes