const ActionTypes = {
   PRODUCTS_LOADING: "PRODUCTS_LOADING",
   PRODUCTS_ERROR: "PRODUCTS_ERROR",
   PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
   SELECTED_CATEGORY: "SELECTED_CATEGORY",
   SELECTED_TAG: "SELECTED_TAG",
   SELECTED_SORT: "SELECTED_SORT",
   EDIT_PRODUCT: "EDIT_PRODUCT",
   CAMPAIGNS_LOADING: "CAMPAIGNS_LOADING",
   CAMPAIGNS_ERROR: "CAMPAIGNS_ERROR",
   CAMPAIGNS_SUCCESS: "CAMPAIGNS_SUCCESS",
   CAMPAIGN_ADD: "CAMPAIGN_ADD",
   CAMPAIGN_DEL: "CAMPAIGN_DEL",
   CAMPAIGN_UPDATE: "CAMPAIGN_UPDATE",
   DASHBOARD_PRODUCTS_SUCCESS: "DASHBOARD_PRODUCTS_SUCCESS",
   DASHBOARD_PRODUCTS_ERROR: "DASHBOARD_PRODUCTS_ERROR",
   DASHBOARD_PRODUCTS_LOADING: "DASHBOARD_PRODUCTS_LOADING",
   DASHBOARD_PRODUCTS_UPDATE: "DASHBOARD_PRODUCTS_UPDATE",
   DASHBOARD_PRODUCTS_NEWADD: "DASHBOARD_PRODUCTS_NEWADD",

}
export default ActionTypes