const ActionTypes = {
   PRODUCTS_LOADING: "PRODUCTS_LOADING",
   PRODUCTS_ERROR: "PRODUCTS_ERROR",
   PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
   PRODUCTS_SORTING: "PRODUCTS_SORTING",
   SELECTED_CATEGORY: "SELECTED_CATEGORY",
   SELECTED_TAG: "SELECTED_TAG",
   EDIT_PRODUCT: "EDIT_PRODUCT",
   DASHBOARD_PRODUCTS_SUCCESS: "DASHBOARD_PRODUCTS_SUCCESS",
   DASHBOARD_PRODUCTS_ERROR: "DASHBOARD_PRODUCTS_ERROR",
   DASHBOARD_PRODUCTS_LOADING: "DASHBOARD_PRODUCTS_LOADING",

}
export default ActionTypes