const CATEGORIES = [
   { key:"boya", value:"Boya", 
      subs:[
         {key:"akrilik", value: "Akrilik Boya"},
         {key:"metalik", value: "Metalik Boya"},
         {key:"efekt", value: "efekt Boya"},
         {key:"yagli", value: "yağlı Boya"},
         {key:"astar", value: "Astar Boya"},
         {key:"yardimci", value: "yardımcı ürünler"},
       ] },
   { key:"firca", value: "Fırça", 
      subs:[
         {key:"zemin", value: "zemin fırçaları"},
         {key:"eskitme", value: "eskitme fırçaları"},
         {key:"rulo", value: "rulo"},
         {key:"stencil", value: "stencil fırçalar"},
         {key:"yelpaze", value: "yelpaze fırçaları"},
         {key:"yagli-boya", value: "yağlı boya fırçaları"},
   ] },
   { key:"vernik", value: "Vernik", 
      subs:[
         {key:"tas", value: "taş vernik"},
         {key:"ultimate", value: "ultimate glaze"},
         {key:"sprey", value: "sprey vernik"},
         {key:"deri", value: "deri verniği"},
         {key:"100kat", value: "100 kat verniği"},
         {key:"siviwax", value: "sıvı wax"},
   ]  },
   { key:"ahsap", value: "Ahşap", 
      subs:[
         {key:"tepsi", value: "tepsi"},
         {key:"kutu", value: "kutu"},
         {key:"sehpa", value: "sehpa"},
         {key:"pano", value: "pano"},
         {key:"fener", value: "fener"},
         {key:"diger", value: "diğer"},
   ]   },
   { key:"boyanabilir", value: "Boyanabilir Obje", 
      subs:[
         {key:"polyester", value: "polyester"},
         {key:"comlek", value: "çömlek"},
         {key:"seramik", value: "seramik"},
         {key:"tas-tozu", value: "taş tozu"},
         {key:"boyali", value: "boyalı ürünler"},
         {key:"yardimci", value: "yardımcı ürünler"},
   ] },
   { key:"hobi", value: "Hobi", 
      subs:[
         {key:"su-kabagi", value: "su kabağı"},
         {key:"ay-pano", value: "ay pano"},
         {key:"zeka-oyunu", value: "zeka oyunu"},
         {key:"mum-malzemeler", value: "mum malzemeler"},
         {key:"tuval", value: "tuval"},
         {key:"punch", value: "punch"},
   ] },
   { key:"el-isi", value: "el İşi ürünler", 
      subs:[
         {key:"kupa", value: "kupa"},
         {key:"fincan", value: "fincan"},
         {key:"kase", value: "kase"},
         {key:"nazarlik", value: "nazarlık"},
         {key:"taki", value: "takı"},
         {key:"diger", value: "diğer"},
   ] },
]
export default CATEGORIES

