const ActionTypes = {
   PRODUCTS_LOADING: "PRODUCTS_LOADING",
   PRODUCTS_ERROR: "PRODUCTS_ERROR",
   PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
   PRODUCTS_CAROUSEL_SUCCESS: "PRODUCTS_CAROUSEL_SUCCESS",
}
export default ActionTypes